version: '3'

services:

  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:8.0.19
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql/config:/etc/mysql/conf.d

  php:
    build: ./php
    container_name: php
    ports:
      - 80:80
    restart: always
    volumes:
      - /home/cnnitouch/www:/var/www/html

  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql:db
    ports:
      - 8989:80
    restart: always

