version: '3'
volumes:
  mysql-volume:

services:
  apache:
    build: ./apache
    container_name: apache
    ports:
      - 80:80
      - 443:443
    privileged: true
    restart: always
    volumes:
      - /home/cnnitouch/html:/var/www/html
      - /mnt:/mnt
      - /mnt/data/shared_data/cnnimages:/var/www/html/cnnimages
      - /home/cnnitouch/certs:/etc/ssl/certs

  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:8.0.19
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql:db
    ports:
      - 8989:80
    restart: always

  util_server:
    build: ../../cnnitouch-util-server
    container_name: util_server
    ports:
      - 8081:8081
      - 8088:8088
      - 8090:8090
      - 8091:8091
    restart: always
    volumes:
      - /home/cnnitouch/html:/var/www/html
      - /mnt:/mnt:rshared
      - /home/cnnitouch/certs:/etc/pki/tls/certs
      - /home/cnnitouch/logs/util_server:/var/log/util_server

  nodetick:
    build: ../../cnnitouch-nodetick
    container_name: nodetick
    ports:
      - 7124:7124/udp
      - 8080:8080
      - 8084:8084
      - 8085:8085
    restart: always
    volumes:
      - /home/cnnitouch/certs:/etc/pki/tls/certs:shared

