version: '3'
volumes:
  mysql-volume:

services:
  php:
    build: ./php
    container_name: php
    ports:
      - 80:80
    privileged: true
    restart: always
    volumes:
      - /home/cnnitouch/html:/var/www/html
      - /mnt:/mnt
      - /mnt/data/shared_data/cnnimages:/var/www/html/cnnimages

  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:8.0.19
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql:db
    ports:
      - 8989:80
    restart: always

